config/routes.rb
GmailAuth::Application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.gender = auth.extra.raw_info.gender
      user.birthday = auth.extra.raw_info.birthday
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])

    session[:user_id] = user.id
    session[:user_name] = user.name
    session[:user_email] = user.email
    session[:image] = user.image
    session[:birthday] = user.birthday
    session[:gender] = user.gender
    redirect_to root_path
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/show.html.erb
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <script type="application/javascript">
    $(document).ready(function () {
      var panels = $('.user-infos');
      var panelsButton = $('.dropdown-user');
      panels.hide();

      //Click dropdown
      panelsButton.click(function () {
        //get data-for attribute
        var dataFor = $(this).attr('data-for');
        var idFor = $(dataFor);

        //current button
        var currentButton = $(this);
        idFor.slideToggle(400, function () {
          //Completed slidetoggle
          if (idFor.is(':visible')) {
            currentButton.html('<i class="glyphicon glyphicon-chevron-up text-muted"></i>');
          }
          else {
            currentButton.html('<i class="glyphicon glyphicon-chevron-down text-muted"></i>');
          }
        })
      });


      $('[data-toggle="tooltip"]').tooltip();

      $('button').click(function (e) {
        e.preventDefault();
        alert("This is a demo.\n :-)");
      });
    });
  </script>

  <script type="text/css">
    .user-row {
    margin-bottom: 14px;
}

.user-row:last-child {
    margin-bottom: 0;
}

.dropdown-user {
    margin: 13px 0;
    padding: 5px;
    height: 100%;
}

.dropdown-user:hover {
    cursor: pointer;
}

.table-user-information > tbody > tr {
    border-top: 1px solid rgb(221, 221, 221);
}

.table-user-information > tbody > tr:first-child {
    border-top: 0;
}


.table-user-information > tbody > tr > td {
    border-top: 0;
}
.toppad
{margin-top:20px;
}



  </script>

  <SCRIPT LANGUAGE="JavaScript">
    function showDate() {
      var now = new Date();
      var days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
      var months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
      var date = ((now.getDate() < 10) ? "0" : "") + now.getDate();

      function fourdigits(number) {
        return (number < 1000) ? number + 1900 : number;
      }

      tnow = new Date();
      thour = now.getHours();
      tmin = now.getMinutes();
      tsec = now.getSeconds();

      if (tmin <= 9) {
        tmin = "0" + tmin;
      }
      if (tsec <= 9) {
        tsec = "0" + tsec;
      }
      if (thour < 10) {
        thour = "0" + thour;
      }

      today = days[now.getDay()] + ", " + date + " " + months[now.getMonth()] + ", " + (fourdigits(now.getYear())) + " - " + thour + ":" + tmin + ":" + tsec;
      document.getElementById("dateDiv").innerHTML = today;
    }
    setInterval("showDate()", 1000);
  </script>

</head>

<body>


<div class="container">
  <div class="row">
    <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
      <% if current_user %>
          Signed in as <strong><%= current_user.name.titleize %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>

          <br>
          <div id="dateDiv"></div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">


            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title"><%= session[:user_name].titleize %></h3>
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-3 col-lg-3 " align="center">
                    <img alt="User Pic" src="<%= session[:image] %>" class="img-circle img-responsive"></div>
                  <div class=" col-md-9 col-lg-9 ">
                    <table class="table table-user-information">
                      <tbody>
                      <tr>
                        <td>Email</td>
                        <td><a href="mailto:<%= session[:user_email] %>"><%= session[:user_email] %></a></td>
                      </tr>



                      <tr>
                        <td>Gender</td>
                        <td><%= session[:gender].titleize %></td>
                      </tr>

                      </tbody>
                    </table>


                  </div>
                </div>
              </div>
              <div class="panel-footer">

              </div>

            </div>
      <% else %>
          <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>

      </div>
      </div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmail Authentication App </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div>
</div>
<div>
  <%= yield %>
</div>
</body>
</html>